# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  application:
    name: helloworld-service
  thymeleaf.cache: false
  main.show-banner: false


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
