# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  application:
    name: helloworld-eureka
  thymeleaf.cache: false
  main.show-banner: false

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF